//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLaunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Voted = new HashSet<Voted>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string LinkImage { get; set; }
    
        public virtual ICollection<Voted> Voted { get; set; }

        public int CountVoted { get; set; }
    }
}
